export const ActionTypes = {
  SET_ADD_EMPLOYEE: "SET_ADD_EMPLOYEE",
  SET_CONTACTS: "SET_CONTACTS",
  SET_SERVICES: "SET_SERVICES",
  SELECTED_SERVICE: "SELECTED_SERVICE",
  SET_TESTIMONIALS: "SET_TESTIMONIALS",
  SET_TEAMS: "SET_TEAMS",
  SET_BANNERS: "SET_BANNERS",
  SET_HOMES: "SET_HOMES",
  // Api call object
  // FETCH_SERVICES: "FETCH_SERVICES",
  // FETCH_Employee: "FETCH_Employee",
  // FETCH_CONTACTS: "FETCH_CONTACTS",
  // FETCH_TESTIMONIALS: "FETCH_TESTIMONIALS",
  // FETCH_TEAMS: "FETCH_TEAMS",
  // FETCH_BANNERS: "FETCH_BANNERS",
  // FETCH_HOMES: "FETCH_HOMES",
};
